name: Scan code with Snyk
on:
  push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true #TODO: Cambiar
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects

      - name: Check current directory
        run: pwd && ls -la

      - name: Create ZIP
        run: zip -r project_code.zip ./
